brainer3220/ITmmunity

app/src/main/java/com/brainer/itmmunity/MainActivity.kt
=> Add auto dark mode for WebView

app/src/main/java/com/brainer/itmmunity/MainActivity.kt
=> After running ContentView Activity, expanded false

app/src/main/java/com/brainer/itmmunity/ContentView.kt
=> Fix ContentHTML Memory leak issue

app/src/main/java/com/brainer/itmmunity/ContentView.kt
=> Add Title view in ContentView

app/src/main/java/com/brainer/itmmunity/MainActivity.kt
=> Fix memory leak issue

app/src/main/java/com/brainer/itmmunity/ContentView.kt
=> Add share option in ContentView

app/build.gradle
=> Update library, and fix Spen issue

app/src/main/java/com/brainer/itmmunity/ContentView.kt
=> Add sign mark

app/src/main/java/com/brainer/itmmunity/MainActivity.kt
=> Add AppBar

app/src/main/java/com/brainer/itmmunity/MainActivity.kt
=> Change to Jetpack Compose design pattern

app/src/main/java/com/brainer/itmmunity/MainActivity.kt
=> Delete first 3 contents for meeco

app/src/main/java/com/brainer/itmmunity/ui/theme/Theme.kt
Added information where to add the color for app bar in light theme and dark theme
=> Updated Theme.kt file

app/src/main/java/com/brainer/itmmunity/Componant/MainViewComponant.kt, app/src/main/java/com/brainer/itmmunity/ContentView.kt, app/src/main/java/com/brainer/itmmunity/Croll/Croll.kt, app/src/main/java/com/brainer/itmmunity/Croll/MeecoNews.kt, app/src/main/java/com/brainer/itmmunity/MainActivity.kt, app/src/main/java/com/brainer/itmmunity/ViewModel/MainViewModel.kt
=> Load more data (paging without paging library)

app/src/main/java/com/brainer/itmmunity/ContentView.kt
=> GlobalScope to CoroutineScope for ContentView

app/src/main/java/com/brainer/itmmunity/Componant/MainViewComponant.kt
Parent issue: https://github.com/brainer3220/ITmmunity/issues/47#issuecomment-1091402683
=> Draw more data for main list

app/build.gradle, app/src/main/java/com/brainer/itmmunity/Componant/MainViewComponant.kt, app/src/main/java/com/brainer/itmmunity/ContentView.kt, app/src/main/java/com/brainer/itmmunity/MainActivity.kt, app/src/main/java/com/brainer/itmmunity/ui/theme/Theme.kt
=> Material to Material3

app/src/main/java/com/brainer/itmmunity/Componant/MainViewComponant.kt
=> Image loading view for MainList

app/src/main/java/com/brainer/itmmunity/Componant/MainViewComponant.kt
=> Change LoadingView param composition to Lottie URL

app/src/main/java/com/brainer/itmmunity/Croll/Croll.kt
=> Replace meeco image url

app/src/main/java/com/brainer/itmmunity/MainActivity.kt
=> Add MainCompose document

app/src/main/java/com/brainer/itmmunity/MainActivity.kt
=> Magic number

app/src/main/java/com/brainer/itmmunity/ViewModel/BackGroundViewModel.kt
=> Add document for BackGroundViewModel

app/src/main/java/com/brainer/itmmunity/Croll/Croll.kt, app/src/main/java/com/brainer/itmmunity/ViewModel/MainViewModel.kt
=> Change htmlToMarkdown parameter

app/src/main/java/com/brainer/itmmunity/Croll/Croll.kt
=> Add getHtml methode document

app/src/main/java/com/brainer/itmmunity/ViewModel/MainViewModel.kt
=> Add document for changeTabletUi method

app/src/main/java/com/brainer/itmmunity/ViewModel/MainViewModel.kt
=> Add changeTitle for MainViewModel

app/src/main/java/com/brainer/itmmunity/MainActivity.kt, app/src/main/java/com/brainer/itmmunity/viewmodel/BackGroundViewModel.kt
=> isConnect to Flow

build.gradle
=> Compose version upgrade

ITmmunity/src/main/java/com/brainer/itmmunity/MainList.kt
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/brainer3220/itmmunity/issues).
=> Apply fixes from CodeFactor

app/build.gradle, app/src/main/java/com/brainer/itmmunity/MainActivity.kt, app/src/main/java/com/brainer/itmmunity/presentation/ContentView.kt, app/src/main/java/com/brainer/itmmunity/presentation/componant/MainViewComponant.kt, app/src/main/java/com/brainer/itmmunity/presentation/viewmodel/ContentViewModel.kt, app/src/main/java/com/brainer/itmmunity/presentation/viewmodel/MainViewModel.kt
=> Pull refresh indicator
